import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>About us</h1>
      <Link href="/">
        <a>Home</a>
      </Link>
      <main className={styles.main}>All Contents for about us</main>

      <footer className={styles.footer}>Nsary Copyright</footer>
    </div>
  );
}
