import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import NsaryLogo from "../assets/nsaryLogo.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nsary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Image
          src={NsaryLogo}
          alt=""
          width="100px"
          height="100%"
          // layout="fill"
          objectFit="contain"
          className={styles.logo}
        />
        <h1>Nsary</h1>
      </header>
      <Link href="/about_us">
        <a>About Us</a>
      </Link>
      <main className={styles.main}>Home page contents</main>
      <footer className={styles.footer}>Nsary</footer>
    </div>
  );
}
